import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import 'tailwindcss/tailwind.css';
import { Providers } from './redux/provider';
export const metadata = {
  title: "Middas library",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar
        /> */}
       <Providers> {children}</Providers></body>
    </html>
  )
}